In [10]:
import numpy as np
import warnings
from tqdm import tqdm

warnings.filterwarnings("ignore")
np.random.seed(17)

In [11]:
n = 2
m = 2
Te = np.random.randn(n,m)     # N~(0, 1)
Te

array([[ 0.27626589, -1.85462808],
       [ 0.62390111,  1.14531129]])

**Пиковая матрциа растояний**

In [12]:
Dp = np.zeros(shape = (n,n))
for p in tqdm(range(n)):
    for q in range(n):
        Dp[p,q] = np.sum(np.abs(Te[p] - Te[q])/(Te[p] + Te[q]))/m
Dp

100%|████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<?, ?it/s]


array([[ 0.        , -1.92157339],
       [-1.92157339,  0.        ]])

**Матрица расстояния Махаланобиса**

In [13]:
Dm = np.zeros(shape = (n,n))
S = np.linalg.inv(np.cov(Te.T))
S

array([[ 2.78119144e+17, -3.22286548e+16],
       [-3.22286548e+16,  3.73468066e+15]])

In [14]:
for p in tqdm(range(n)):
    for q in range(n):
        Dm[p,q] = np.sqrt(np.dot(np.dot((Te[p] - Te[q]).T, S), (Te[p] - Te[q])))
Dm

100%|███████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 501.44it/s]


array([[0.        , 0.57397573],
       [0.57397573, 0.        ]])

**Або**

In [15]:
from scipy.spatial import distance

In [16]:
Dm_2 = np.zeros(shape = (n,n))
for p in tqdm(range(n)):
    for q in range(n):
        Dm_2[p,q] = distance.mahalanobis(Te[p], Te[q], S)
Dm_2

100%|████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<?, ?it/s]


array([[0.        , 0.57397573],
       [0.57397573, 0.        ]])